# Generated by Django 4.1 on 2022-09-15 23:54

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("htmx_lookup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
